server:
  port: 8088
dubbo:
  application:
    name: dubbo-client
    qosPort: 22221
  # 使用 zookeeper 注册中心暴露服务，注意要先开启 zookeeper
  # 注册中心id
  registry:
    id: zookeeper-registry
    # 注册中心协议
    protocol: zookeeper
    # 注册中心地址
    address: 127.0.0.1:2181

  # dubbo协议在20882端口暴露服务
  # 协议名称
  protocol:
    name: dubbo
    # 协议端口
    port: 20882